### PR TITLE
Added a '/town delete' command

### PR DESCRIPTION
**Pull request by PureTryOut**
Towns can now be deleted using `/town delete` or `/town delete {townname}`. Not specifying which town should be deleted delete's the players own town **if** he is the owner.

If a town is specified it will check if the player has the extra permission `townvalds.town.delete.other`. If the player does, the town will be deleted, no matter if it's his own town or not. This is mainly meant for server moderators.

Resolves "Delete towns by /town delete" in #58

Please check if this could be done more efficient before merging, as I'm not sure the code is properly done. My brain farted every time I started on this.

### CODE REVIEW

**Comment by ghost** [comment]
I'm not sure if sqlite can azide this, but at least for mysql there is something I think called foreign keys, which makes sure that in a specific table every record has to have a valid record in another table. If you create a new chunk for example after a proper setup it has to carry a valid town id. Additionally, if you remove this town, all linked records can be deleted too.

**Comment by PureTryOut** [comment]
Yeah I know it's there in MySQL.

```
ALTER TABLE townChunks
ADD FOREIGN KEY (town_id) REFERENCES towns(town_id)
```

Not sure if that works with Sqlite to be honest, let's try that out.

**Comment by PureTryOut** [comment]
So creating a foreign key connection between `townChunks` and `towns` on `town_id`, with `ON UPDATE CASCADE` and `ON DELETE CASCADE` set, seems to work fine. However, when actually deleting the town, the related townChunks are not deleted as well. This while [the Sqlite documentation](https://sqlite.org/foreignkeys.html#fk_actions) shows it should work. This happens both when doing it by code, and by running a query manually.

I guess we're stuck with doing it ourselves by individual queries...

**Comment by omarroth** [comment]
Looking at the docs [here](https://www.sqlite.org/foreignkeys.html#fk_enable), it seems like foreign keys are disabled by default. Try running `PRAGMA foreign_keys = ON` before creating the DB if you haven't already.

**Comment by PureTryOut** [comment]
@omarroth thanks, that did the job! I just added that command to the initial database creation queries. I'll update all code to make use of foreign keys in another PR.

**Pull request merged**
