### PR TITLE
Updated pom.xml to use Spigot as a Maven dependency

### PR DESCRIPTION
**Pull request by PureTryOut**
Updated pom.xml to use Spigot as a Maven dependency instead of having it in the build path.
It now builds against Spigot and Bukkit 1.8.6-R0.1-SNAPSHOT

### CODE REVIEW

**Comment by thesbros** [comment]
Three things:
* You don't need Bukkit, spigot-api == bukkit.
* Why'd you add a random trailing whitespace?
* The url should should just be https://hub.spigotmc.org/nexus/content/groups/public

**Comment by PureTryOut** [comment]
- Yes I know it is, however I found somewhere it was needed for certain API calls. I can't recall the source right now but i'll search for it tomorrow
- Not sure. I saw it in the commit, but it doesn't hurt anything so I just left it
- Maybe, this works too though. Any reason of using one over the other?

**Comment by thesbros** [comment]
* I am 100% sure it's not. Only if you're using NMS (modifying the core game mechanics), which we're not and probably never will be, and even then it's craftbukkit you would want, not bukkit.
* Trailing whitespace is usually just a bad and annoything thing to have in your code.
* The link I sent to you in the other issue was to show you it was in the repo. The one I just sent you is the actual repo link, containing everything in that repo. I'm not even sure why it works.

**Comment by PureTryOut** [comment]
Well I removed the whitespace and the Bukkit dependency. However, i'm having kind of a weird problem. Yesterday on my desktop it build fine, it was able to find the correct dependencies on the wrong url. Today i'm trying to build on my laptop, and it fails to find the correct dependencies. I've changed the url to the correct one, but that failed too.
```[ERROR] Failed to execute goal on project Townvalds: Could not resolve dependencies for project com.linuxmasterrace:Townvalds:jar:0.0.1: Failure to find org.spigotmc:spigot-api:jar:1.8.6-R0.1-SNAPSHOT in https://hub.spigotmc.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of spigot-repo has elapsed or updates are forced -> [Help 1]```

This is basically the same error as I've described [here](http://www.spigotmc.org/threads/solved-trouble-setting-up-new-bukkit-spigot-plugin.68563/#post-756798), which was then fixed by adding the jars itself to the build path. I can't check on my desktop at the moment since it's at home, but I wonder why it did work there. I can access the url in my browser, so it's not blocked or soemthing.

**Comment by thesbros** [comment]
It says it was cached, delete your Maven cache and try it again.

**Comment by PureTryOut** [comment]
Yup that worked, should've thought of it myself. Is everything now correct?

**Comment by thesbros** [comment]
The indentation is inconsistent in the pom.xml, but otherwise LGTM.

**Pull request merged**
