### PR TITLE
Clean up code for toggling town settings

### PR DESCRIPTION
**Pull request by omarroth**
Changed /town toggle so that it will list all toggleable properties instead of returning an error message. Also makes it easier to add more properties in the future.

### CODE REVIEW

**Comment by PureTryOut** [comment]
Why do you set the database value to "off" instead of 0 what you did before? 0 (off) and 1 (on) is imo more clear, and less error prone (what if a user enters it in the database manually and doesn't notice a typo for example). "off" and "on" in the command itself is fine though.

**Comment by omarroth** [comment]
I think that 0 and 1 is better if the user doesn't have to type it in the command. If we want to more directly model Towny, then it should be "/town toggle explosions", without the 0 or 1.

**Comment by PureTryOut** [comment]
Without the 0 or 1 would probably be best. Just save it in the database as 0 or 1 instead of "off" or "on".

**Comment by omarroth** [comment]
Fixed.

**Comment by PureTryOut** [comment]
Looks great, merged.

**Pull request merged**
