### PR TITLE
Add pvp toggle

### PR DESCRIPTION
**Pull request by omarroth**
All players inside town boundaries cannot take damage from other players and will not be knocked back, however they will still glow red when punched.  

PvP is disabled by default.

### CODE REVIEW

**Comment by Avamander** [comment]
Is there a reason the glow is still there?

**Comment by omarroth** [comment]
Currently, an attack from another player is zeroed when received, but the server still processes it.

**Comment by Avamander** [comment]
Are potion arrows', potions' or enchanted weapons' special effects also
zeroed?

**Comment by omarroth** [comment]
Enchanted weapons are, the rest are not zeroed as they could also come from mobs (skeletons and witches respectively).

**Comment by Avamander** [comment]
I think it should still somehow be dealt with because it's still PvP if I
kill someone with damage potions or potion arrows.

**Comment by PureTryOut** [comment]
From the documentation on HOOK_TAKE_DAMAGE:
`If the function returns true, no other callbacks are called, and no damage nor effects are applied.`

You instead seem to set damage to 0 manually. Can't you just return true instead?

**Comment by omarroth** [comment]
Didn't see that. Doing that should get rid of the rid glow. Also the docs on cProjectileEntity contain an undocumented GetCreatorName which should return etPlayer or similar.

**Comment by PureTryOut** [comment]
Also look into cancelling player damage for players outside a pvp-free zone, when the hitting arrow or potion is fired/thrown from within a pvp-free zone. Otherwise players can just build walls in pvp-free zones and shoot arrows out from there, and abuse the system.

**Comment by omarroth** [comment]
Players no longer glow red when attacked by arrows or handheld weapons. Potions still work however, because it doesn't seem possible to get the type of entity that created a cSplashPotionEntity. Replacing the pvp toggle with a generic damage setting might be better.

**Comment by PureTryOut** [comment]
2 things left (except for the potion part):
- If town_pvp_enabled is null in the database, the command won't do anything. This is however no problem if you set it to be 1 by default
- When a player from outside a protected town hits a person inside a protected town, the damage is processed normally. Maybe make a check that both of the players have to be outside the pvp-free zone

**Comment by omarroth** [comment]
- Town_pvp_enabled is set to 0 by default.
- Players will no longer take damage if either one of them is in an area where pvp is disabled.

**Comment by PureTryOut** [comment]
Sorry, kinda forgot about it ;)

Works good, code clean, merging.

**Pull request merged**
