### PR TITLE
Added toggleable explosions

### PR DESCRIPTION
**Pull request by omarroth**
TNT and mob explosions can be disabled in a town while a player is in that town with the command
`/town toggle explosions <0 or 1>`

### CODE REVIEW

**Comment by PureTryOut** [comment]
Looks good, although you seem to have added a lot of spaces/tabs everywhere, any reason for that?

Will test this out tomorrow, and then probably merge it.

**Comment by omarroth** [comment]
Just tried to switch some of the spaces to tabs, might split that into a seperate commit.

**Comment by PureTryOut** [comment]
It seems that once you're in a town (no matter if they have explosions enabled or not), nothing explodes anymore. From my understanding TNT and Creepers should still explode with `town_explosions_enabled` right?

**Comment by omarroth** [comment]
That's correct, it should work properly now.

**Comment by PureTryOut** [comment]
Awesome, works fine now! Merged.

**Pull request merged**
