### PR TITLE
Renamed 'townChunks' to 'plots'

### PR DESCRIPTION
**Pull request by PureTryOut**
Renamed 'townChunks' to 'plots' where applicable. The latter name fits better and better describes what it is.

### CODE REVIEW

**Comment by PureTryOut** [comment]
I just noticed I got a lot of commits left over from #77... Anybody any clue how to get rid of those?

**Comment by omarroth** [comment]
It looks like the master that plots is comparing against is outdated. You might try rebasing against upstream with something like  
`git pull upstream master --rebase`

**Comment by PureTryOut** [comment]
That did not really fix much lol... Well at least I tried.

Seems like at least the proper changes are in this PR, and merging shouldn't mess much up. We'll squash it into 1 commit like we do with the rest.

**Comment by PureTryOut** [comment]
Approved by @random-nick

**Pull request merged**
